<?php

namespace VOOTS\IndexBundle\Repository;

/**
 * coupdecoeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coupdecoeurRepository extends \Doctrine\ORM\EntityRepository
{
}
