<?php

namespace VOOTS\IndexBundle\Repository;

/**
 * explicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class explicationRepository extends \Doctrine\ORM\EntityRepository
{
      public function getOneExplicationWithTagsArray(array $tagsNames)
  {
    $qb = $this->createQueryBuilder('a');

    $qb
      ->innerJoin('a.tagPrincipal', 'c')
      ->addSelect('c')
    ;

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where($qb->expr()->in('c.nom', $tagsNames));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getOneOrNullResult();
  }
    
}
