<?php

namespace VOOTS\IndexBundle\Repository;

/**
 * minivootsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class minivootsRepository extends \Doctrine\ORM\EntityRepository
{
    
  public function getMinivootsWithTagsArray(array $tagsNames)
  {
    $qb = $this->createQueryBuilder('a');

    // On fait une jointure avec l'entité Category avec pour alias « c »
    $qb
      ->innerJoin('a.tags', 'c')
      ->addSelect('c')
    ;

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where($qb->expr()->in('c.nom', $tagsNames));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY)
    ;
  }
}
