<?php

namespace VOOTS\IndexBundle\Repository;

/**
 * tagsAssociesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tagsAssociesRepository extends \Doctrine\ORM\EntityRepository
{
}
