voots_index_homepage:
    path:     /
    defaults: { _controller: VOOTSIndexBundle:Index:index }
    
voots_index_apropos:
    path:     /a-propos
    defaults: { _controller: VOOTSIndexBundle:Index:apropos }

voots_index_contact:
    path:     /contact
    defaults: { _controller:  VOOTSIndexBundle:Index:contact }
    
voots_index_associations:
    path:     /associations
    defaults: { _controller:  VOOTSIndexBundle:Index:associations }
    
voots_index_page:
    path:     /{tag}
    defaults: { _controller:  VOOTSIndexBundle:Index:pageStandard }